// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Headers$BsHeaders = require("./Headers.bs.js");

console.log("Hello, BuckleScript and Reason!");

console.log("myHeaders1", Headers$BsHeaders.myHeaders1(/* () */0));

console.log("myHeaders2", (function (param) {
        return Headers$BsHeaders.myHeaders2(/* () */0, param);
      }));

console.log("headers", new Headers());

/*  Not a pure module */
