// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var myHeaders = new Headers();

function myHeaders1(param) {
  return myHeaders.append("Content-Type", "image/jpeg");
}

function myHeaders2(param, param$1) {
  return param$1.append(myHeaders, "Content-Type", "image/jpeg");
}

console.log("myHeaders1", myHeaders1(/* () */0));

console.log("myHeaders2", (function (param) {
        return myHeaders2(/* () */0, param);
      }));

console.log("headers", new Headers());

exports.myHeaders = myHeaders;
exports.myHeaders1 = myHeaders1;
exports.myHeaders2 = myHeaders2;
/* myHeaders Not a pure module */
